<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage2.master" AutoEventWireup="true" CodeFile="interface-team.aspx.cs" Inherits="Default2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <style>
        .button{float:left;line-height:50px;}
        .CMC{float:left;padding-right:30px}

        body {
            text-align: center;
        }

        .container {
            border: 2px solid #cdcdcd;
            border-radius: 2px;
            padding: 20px;
            margin-right: 200px;
            margin-bottom: 20px;
        }

        .container .message-list {
            background-color: #f3f3f3;
            border-radius: 2px;
            height: 300px;
            width: 100%;
            border: 2px solid #cdcdcd;
            overflow: auto;
            text-align: left;
        }

        .container .message-list #discussion {
            list-style-type: none;
        }

        .container .message-list #discussion li {
            line-height: initial;
        }

        .container .action {
            padding-top: 10px;
        }

        .container .action #message {
            border-radius: 2px;
            width: calc(100% - 158px);
            border: 2px solid #cdcdcd;
            height: 36px;
            padding: 0 10px;
            box-sizing: border-box;
        }

        .container .action #sendmessage {
            border-radius: 2px;
            cursor: pointer;
            border: 2px solid #cdcdcd;
            width: 150px;
            height: 36px;
            background-color: #eee;
            margin: 0;
        }

        .container .action #sendmessage:hover {
            background-color: #f3f3f3;
        }
    </style>
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val('<%=Session["username"].ToString() %>');
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
    </script>
   <div class="button">
       <div>
            <asp:Button ID="Button3" runat="server" Text="基本資料" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface.aspx"/>
       </div>
       <div>
            <asp:Button ID="Button2" runat="server" Text="我的好友" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-friend.aspx"/>
       </div>
        <div>
            <asp:Button ID="Button13" runat="server" Text="我的收藏用戶" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-collection.aspx"/>
       </div>
       <div>
           <asp:Button ID="Button14" runat="server" Text="我的收藏案件" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-collectionC.aspx" />
       </div>
       <div>
           <asp:Button ID="Button15" runat="server" Text="我的收藏論帖" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-collectionF.aspx" />
       </div>
       <div>
            <asp:Button ID="Button6" runat="server" Text="我的黑名單" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-blacklist.aspx"/>
       </div>
       <div>
            <asp:Button ID="Button7" runat="server" Text="我的團隊" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''"  style="border-top-left-radius: 20px;border-bottom-right-radius: 20px;" Width="120px" PostBackUrl="~/Interface-team.aspx"/>
       </div>
   </div>
            
    <div style="float:right;">
         <asp:Image ID="Image1" runat="server" ImageAlign="Middle" ImageUrl="~/image/放大鏡(已去底).png" Height="20px" />
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="搜尋" BackColor="Black"  BorderStyle="Ridge"  Font-Names="微軟正黑體" Font-Size="12pt" ForeColor="White" onmouseover="this.style.fontWeight='bold'"  onmouseout="this.style.fontWeight=''" />
    </div>

    <div class="collection-type" style="line-height:50px;padding-left:200px">
        <div class="title">          
             <asp:label runat="server" Font-Bold="True">我的團隊</asp:label>   
         </div>
        <h2 style="text-align: left;margin-right: 200px;">300017 血鎮</h2>
        <div class="container">
            <div class="message-list">
                <ul id="discussion"></ul>
            </div>
            <div class="action">
                <input type="text" id="message" />
                <input type="button" id="sendmessage" value="Send" />
            </div>
            <input type="hidden" id="displayname" />
        </div>
    </div>

    </asp:Content>

